const verbs = [
  { spanish: 'comer', english: 'eat', reg: true },
  { spanish: 'llamar', english: 'call', reg: true },
  { spanish: 'mostrar', english: 'show', group: 3 },
  { spanish: 'creer', english: 'believe', reg: true },
  { spanish: 'recordar', english: 'remember', group: 3 },
  {
    spanish: 'venir',
    english: 'come over',
    group: 1,
    yo: 'vengo',
    tu: 'vienes',
    el: 'viene',
    noso: 'venimos',
    ellos: 'vienen'
  },
  { spanish: 'almorzar', english: 'eat lunch', group: 3 },
  {
    spanish: 'oir',
    english: 'hear',
    group: 1,
    yo: 'oigo',
    tu: 'oyes',
    el: 'oye',
    noso: 'oimos',
    ellos: 'oyen'
  },
  { spanish: 'reir', english: 'laugh', group: 4 },
  { spanish: 'vender', english: 'sell', reg: true },
  { spanish: 'salir', english: 'leave', group: 5, yo: 'salgo' },
  { spanish: 'confesar', english: 'confess', group: 2 },
  { spanish: 'saber', english: 'know', group: 5, yo: 'sé' },
  { spanish: 'sacar', english: 'take out', reg: true },
  { spanish: 'correr', english: 'run', reg: true },
  { spanish: 'morir', english: 'die', group: 3 },
  { spanish: 'servir', english: 'serve', group: 4 },
  { spanish: 'prometer', english: 'promise', reg: true },
  { spanish: 'viajar', english: 'travel', reg: true },
  { spanish: 'enseñar', english: 'teach', reg: true },
  { spanish: 'recomendar', english: 'recommend', group: 2 },
  { spanish: 'jugar', english: 'play', group: 3, ueIndex: 1 },
  { spanish: 'dar', english: 'give', group: 5, yo: 'doy' },
  { spanish: 'escribir', english: 'write', reg: true },
  { spanish: 'hablar', english: 'speak', reg: true },
  { spanish: 'contestar', english: 'answer', reg: true },
  { spanish: 'pensar', english: 'think', group: 2 },
  { spanish: 'perder', english: 'lose/waste/miss (the bus)', group: 2 },
  { spanish: 'mirar', english: 'look', reg: true },
  { spanish: 'ganar', english: 'win', reg: true },
  { spanish: 'aprender', english: 'learn', reg: true },
  { spanish: 'contar', english: 'sing', reg: true },
  { spanish: 'leer', english: 'read', reg: true },
  { spanish: 'costar', english: 'cost', group: 3 },
  { spanish: 'permitir', english: 'permit', reg: true },
  { spanish: 'visitar', english: 'visit', reg: true },
  { spanish: 'comprender', english: 'understand', reg: true },
  { spanish: 'vivir', english: 'live', reg: true },
  { spanish: 'devolver', english: 'give back', group: 3 },
  { spanish: 'terminar', english: 'finish', reg: true },
  { spanish: 'decorar', english: 'decorate', reg: true },
  { spanish: 'recibir', english: 'receive', reg: true },
  { spanish: 'cerrar', english: 'close', group: 2 },
  { spanish: 'responder', english: 'reply/respond', reg: true },
  { spanish: 'comenzar', english: 'begin', group: 2 },
  { spanish: 'quedar', english: 'stay', reg: true },
  { spanish: 'poner', english: 'put', group: 5, yo: 'pongo' },
  { spanish: 'sonar', english: 'make a sound', group: 3 },
  { spanish: 'contar', english: 'count', group: 3 },
  { spanish: 'volar', english: 'fly', group: 3 },
  { spanish: 'partir', english: 'leave', reg: true },
  { spanish: 'decidir', english: 'decide', reg: true },
  { spanish: 'pagar', english: 'pay', reg: true },
  { spanish: 'hacer', english: 'do', group: 5, yo: 'hago' },
  { spanish: 'asistir', english: 'assist/attend', reg: true },
  { spanish: 'insistir', english: 'insist', reg: true },
  { spanish: 'conocer', english: 'know knowledge', group: 5, yo: 'conozco' },
  { spanish: 'esconder', english: 'hide', reg: true },
  { spanish: 'entrar', english: 'enter', reg: true },
  { spanish: 'repetir', english: 'repeat', group: 4 },
  { spanish: 'borrar', english: 'erase', reg: true },
  { spanish: 'dormir', english: 'sleep', group: 3 },
  { spanish: 'volver', english: 'come back/return', group: 3 },
  { spanish: 'resolver', english: 'resolve', group: 3 },
  { spanish: 'cubrir', english: 'cover', reg: true },
  { spanish: 'arreglar', english: 'fix', reg: true },
  { spanish: 'poder', english: 'can', group: 3 },
  { spanish: 'celebrar', english: 'celebrate', reg: true },
  { spanish: 'encontrar', english: 'find/meet', group: 3 },
  { spanish: 'necesitar', english: 'need', reg: true },
  { spanish: 'explicar', english: 'explain', reg: true },
  { spanish: 'pedir', english: 'ask for/demand/require', group: 4 },
  { spanish: 'llevar', english: 'wear', reg: true },
  { spanish: 'escuchar', english: 'hear', reg: true },
  { spanish: 'empezar', english: 'start', group: 2 },
  {
    spanish: 'tenir',
    english: 'have',
    group: 1,
    yo: 'tengo',
    tu: 'tienes',
    el: 'tiene',
    noso: 'tenemos',
    ellos: 'tienen'
  },
  { spanish: 'descansar', english: 'rest', reg: true },
  { spanish: 'sentir', english: 'feel/be sorry', group: 2 },
  { spanish: 'patinar', english: 'skate', reg: true },
  { spanish: 'cominar', english: 'walk', reg: true },
  { spanish: 'beber', english: 'drink', reg: true },
  { spanish: 'ayudar', english: 'help', reg: true },
  { spanish: 'estudiar', english: 'study', reg: true },
  { spanish: 'invidar', english: 'invite', reg: true },
  { spanish: 'sonreir', english: 'smile', group: 4 },
  { spanish: 'comprar', english: 'buy', reg: true },
  { spanish: 'medir', english: 'measure', group: 4 },
  { spanish: 'regrasar', english: 'return', reg: true },
  { spanish: 'referir', english: 'refer', group: 2 },
  { spanish: 'pasar', english: 'happen/to spend time', reg: true },
  { spanish: 'entender', english: 'understand', group: 2 },
  { spanish: 'montar', english: 'ride', reg: true },
  { spanish: 'tocar', english: 'touch', reg: true },
  {
    spanish: 'decir',
    english: 'say',
    group: 1,
    yo: 'digo',
    tu: 'dices',
    el: 'dice',
    noso: 'decimos',
    ellos: 'dicen'
  },
  { spanish: 'admirar', english: 'admire', reg: true },
  { spanish: 'preparar', english: 'prepare', reg: true },
  { spanish: 'dibujar', english: 'draw', reg: true },
  { spanish: 'sufrir', english: 'suffer', reg: true },
  { spanish: 'usar', english: 'use', reg: true },
  { spanish: 'ovidar', english: 'forget', reg: true },
  { spanish: 'bailar', english: 'dance', reg: true },
  { spanish: 'cocinar', english: 'cook', reg: true },
  { spanish: 'tomar', english: 'take', reg: true },
  { spanish: 'defender', english: 'defend', group: 2 },
  { spanish: 'abrir', english: 'open', reg: true },
  { spanish: 'gritar', english: 'shout', reg: true },
  { spanish: 'querer', english: 'want', group: 2 },
  { spanish: 'preferir', english: 'prefer', group: 2 },
  { spanish: 'subir', english: 'go up/climb', reg: true },
  { spanish: 'buscar', english: 'search/look for', reg: true },
  { spanish: 'cambiar', english: 'change', reg: true },
  { spanish: 'ir', english: 'go', group: 1,
    yo: 'voy',
    tu: 'vas',
    el: 'va',
    noso: 'vamos',
    ellos: 'van',
  },
  { spanish: 'preguntar', english: 'question', reg: true },
  { spanish: 'bajar', english: 'descend/go down', reg: true },
  { spanish: 'nadar', english: 'swim', reg: true },
  { spanish: 'desear', english: 'wish', reg: true },
  { spanish: 'lavar', english: 'wash', reg: true },
  { spanish: 'trabajar', english: 'work', reg: true },
  { spanish: 'cantar', english: 'sing', reg: true },
  { spanish: 'cortar', english: 'cut', reg: true },
  { spanish: 'practicar', english: 'practice', reg: true },
  { spanish: 'traer', english: 'bring', group: 5, yo: 'traigo' }
];
